import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Nav from "../components/homepage/Nav";
import Footer from "../components/homepage/Footer";
import { useEffect } from "react";
import { useRouter } from "next/router";
import AuthShowcase from "../components/auth/AuthButton";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from PrayerBox" });

  const session = useSession();
  const router = useRouter();
  useEffect(() => {
    if (session.status === "authenticated") {
      router.push("/dashboard");
    }
  }, [session, router]);

  return (
    session.status === "unauthenticated" && (
      <>
        <Head>
          <title>PrayerBox ✨</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              Prayer<span className="text-[hsl(52,100%,70%)]">Box</span>
            </h1>
            <div className="flex flex-col items-center gap-2">
              <p className="text-2xl text-white">
                {hello.data ? hello.data.greeting : "Loading tRPC query..."}
              </p>
              <AuthShowcase />
            </div>
          </div>
        </main>
        <Footer />
      </>
    )
  );
};

export default Home;
