import Head from "next/head";
import Nav from "../components/layout/Nav";
import Footer from "../components/layout/Footer";
import { useEffect } from "react";
import { useRouter } from "next/router";
import AuthButton from "../components/auth/AuthButton";
import { useSession } from "next-auth/react";
import { api } from "../utils/api";
import PrayerRequest from "../components/prayerRequest/PrayerRequest";


const Home: any = () => {
  const hello = api.example.hello.useQuery({ text: "from PrayerBox" });

  const session = useSession();
  const router = useRouter();
  useEffect(() => {
    if (session.status === "authenticated") {
      router.push("/dashboard");
    }
  }, [session, router]);

  return (
    session.status === "unauthenticated" && (
      <>
        <Head>
          <title>PrayerBox ✨</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col items-center justify-center bg-blue-100 dark:bg-slate-800">
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-8 md:py-12 ">
            <h1 className="text-5xl font-extrabold tracking-tight text-slate-600 dark:text-white sm:text-[5rem]">
              Prayer<span className="text-orange-400 dark:text-[hsl(52,100%,70%)]">Box</span>
            </h1>
          </div>
          <div className="prayer pb-10">
            <PrayerRequest />
          </div>
        </main>
      </>
    )
  );
};

export default Home;
